export const routes = {
  auth: {
    auth: '/(auth)/auth',
    register: '/(auth)/register',
    forgot_pwd: '/(auth)/forgot-password',
    verifyOtp: '/(auth)/verify-otp',
    onboard: '/(auth)/onboard',
    update_password: '/(auth)/update-password',
  },
  'oauth-callback': '/oauth-callback',
  user: {
    profile: '/(hydrogen)/(profile)',
    account_settings: '/(hydrogen)/(accounts)',
    settings: '/(hydrogen)/(settings)',
    security: '/(hydrogen)/(security)',
    timezone: '/(hydrogen)/(timezone)',
    position_calculator: '/(hydrogen)/(position-calculator)',
    support_inbox: '/(hydrogen)/(support-inbox)',
    singleSupport: (id: string) => `/(hydrogen)/(support-inbox)/details/${id}`,
    tags: '/(hydrogen)/(tags)',
    add_trade: '/(hydrogen)/(add-trade)',
    search: '/(hydrogen)/search',
  },
  tabs: {
    tabs: '/(hydrogen)/(tabs)',
    home: '/(hydrogen)/(tabs)/home',
    category: '/(hydrogen)/(tabs)/category',
    // sell: '/(hydrogen)/(tabs)/sell',
    chat: '/(hydrogen)/(tabs)/chat',
    profile: {
      profile: '/(hydrogen)/(tabs)/profile',
      'select-language': '/(hydrogen)/(tabs)/profile/select-language',
    },
    create_profile: '/(hydrogen)/create-profile',
    post: '/(hydrogen)/(tabs)/post',
    singlePost: (id: string) => `/singlePost/${id}`,
    chatScreen: (id: string) => `/chat-screen/${id}`,
    preview_post: '/(hydrogen)/(tabs)/post/preview-post',
    success_view: '/(hydrogen)/(tabs)/post/success-view',
    favourites: '/(hydrogen)/favourites',
    notification: '/(hydrogen)/notifications',
    post_list: '/(hydrogen)/post-list',
    help_support: '/(hydrogen)/help-support',
    single_user_profile: '/(hydrogen)/single-user-profile',
  },
  'select-language': '/select-language',
  success: '/(hydrogen)/success',
  paymentSuccess: (id: any) => `/(hydrogen)/payment-success/${id}`,
};
